# Generated by Django 4.2.3 on 2023-07-26 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='deadline_datetime',
            new_name='deadline',
        ),
    ]
